name: Weekly Docker Build and Push

on:
  schedule:
    # Run at 08:08 AM every Monday (you can adjust the time/day as needed)
    - cron: '8 8 * * MON'
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository buildenvs
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--buildenvs
          path: containers-tools/buildenvs

      - name: Checkout Repository helpers
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--helpers
          path: containers-tools/helpers

      - name: Validating situation
        run: sh -c "set -x && pwd && ls -lA && ls -lA containers-tools && ls -lA containers-tools/buildenvs && ls -lA containers-tools/helpers"

      - name: Set up Bootstrap Environment
        run: |
          echo -e 'FROM debian:testing\nRUN --mount=type=bind,source=containers-tools/buildenvs,target=/data sh -c "set -x && ls -lA /data && sh /data/bootstrap.sh"' > bootstrap.dockerfile && \
          DOCKER_BUILDKIT=1 docker build -t bootstrap-image -f bootstrap.dockerfile .

      - name: Build Container image
        run: |
          docker run --privileged --rm -v "${GITHUB_WORKSPACE}:/data" bootstrap-image \
          sh -c "
            cd /data &&
            buildah bud -f /data/containers-tools/buildenvs/buildenvwine.sh -t buildenvwine:latest . &&
            buildah login -u vaspian -p TOKEN docker.io &&
            buildah tag buildenvwine:latest docker.io/vaspian/buildenvwine:latest &&
            buildah push docker.io/vaspian/buildenvwine:latest
          "
