name: Weekly Docker Build and Push

on:
  schedule:
    # Run at 08:08 AM every Monday (you can adjust the time/day as needed)
    - cron: '8 8 * * MON'
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository buildenvs
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--buildenvs
          path: ${GITHUB_WORKSPACE}/containers-tools/buildenvs

      - name: Checkout Repository helpers
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--helpers
          path: ${GITHUB_WORKSPACE}/containers-tools/helpers

      - name: Validating situation
        run: sh -c "pwd && ls -lA"

      - name: Set up Bootstrap Environment
        run: |
          echo -e 'FROM debian:testing\nRUN --mount=type=bind,source=${GITHUB_WORKSPACE}/containers-tools/buildenvs/bootstrap.sh,target=/data/bootstrap.sh sh /data/bootstrap.sh' | DOCKER_BUILDKIT=1 docker build -t bootstrap-image -

      - name: Build Container image
        run: |
          docker run --privileged --rm -v "${GITHUB_WORKSPACE}:/data" bootstrap-image \
          sh -c "
            cd /data &&
            buildah bud -f /data/containers-tools/buildenvs/buildenvwine.sh -t buildenvwine:latest . &&
            buildah login -u vaspian -p TOKEN docker.io &&
            buildah tag buildenvwine:latest docker.io/vaspian/buildenvwine:latest &&
            buildah push docker.io/vaspian/buildenvwine:latest
          "
