name: Weekly Docker Build and Push

on:
  schedule:
    # Run at 08:08 AM every Monday (you can adjust the time/day as needed)
    - cron: '8 8 * * MON'
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository buildenvs
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--buildenvs
          path: containers-tools/buildenvs

      - name: Checkout Repository helpers
        uses: actions/checkout@v4
        with:
          repository: flucas1/containers-tools--helpers
          path: containers-tools/helpers

      - name: Build Container image
        run: docker build -t yourusername/yourimagename:latest ./buildenvs/buildenvwine.dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Container image
        run: docker push yourusername/yourimagename:latest
